# Generated by Django 5.1.3 on 2025-09-03 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_districtmodel_regionmodel_user_district_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'CountryModel',
                'verbose_name_plural': 'CountryModels',
                'db_table': 'country',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='district',
        ),
        migrations.AddField(
            model_name='regionmodel',
            name='country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.countrymodel'),
        ),
        migrations.AddField(
            model_name='user',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.countrymodel'),
        ),
        migrations.DeleteModel(
            name='DistrictModel',
        ),
    ]
