# Generated by Django 5.1.3 on 2025-09-06 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='qrcode',
            field=models.ImageField(blank=True, null=True, upload_to='qrcode', verbose_name='qrcode'),
        ),
    ]
