# Generated by Django 5.1.3 on 2025-09-22 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_countrymodel_name_en_countrymodel_name_ru_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='countrymodel',
            name='code',
            field=models.CharField(max_length=10, null=True, verbose_name='code'),
        ),
        migrations.AddField(
            model_name='countrymodel',
            name='flag',
            field=models.ImageField(null=True, upload_to='flag/', verbose_name='flag'),
        ),
    ]
