# Generated by Django 5.1.3 on 2025-10-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_countrymodel_code_countrymodel_flag'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='href',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='href'),
        ),
    ]
