networks:
  vesbini_test:
    driver: bridge

volumes:
  pg_data: null
  pycache: null

services:
  web:
    networks:
      - vesbini_test 
    build:
      context: .
      dockerfile: ./docker/Dockerfile.web
      args:
        SCRIPT: ${SCRIPT:-entrypoint.sh}
    restart: always
    environment:
      - PYTHONPYCACHEPREFIX=/var/cache/pycache
      - SCRIPT=${SCRIPT:-entrypoint.sh}
    volumes:
      - pycache:/var/cache/pycache
    depends_on:
      - db
      - redis
  db:
    networks:
      - vesbini_test 
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: django
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "2309"
    volumes:
      - pg_data:/var/lib/postgresql/data
  redis:
    networks:
      - vesbini_test 
    restart: always
    image: redis
