[tool.black]
line-length = 120

[tool.isort]
profile = "black"
line_length = 120

[tool.pytest.ini_options]
DJANGO_SETTINGS_MODULE = "config.settings.local"
python_files = "tests.py test_*.py *_tests.py"
filterwarnings = [
    "ignore::DeprecationWarning",
    "ignore::PendingDeprecationWarning",
    "ignore::ResourceWarning",
    "ignore::Warning" # This line will ignore all warnings
]


[tool.flake8]
max-line-length = 120
ignore = ["E701", "E704", "W503"]

[tool.pyright]
typeCheckingMode = "basic"
reportMissingImports = false
reportMissingTypeStubs = false
pythonVersion = "3.12"
