# Generated by Django 5.1.3 on 2025-09-27 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historymodel',
            name='comment',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='comment'),
        ),
    ]
