FROM jscorptech/django:v0.5

ARG SCRIPT="entrypoint.sh"
ENV SCRIPT=$SCRIPT

ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000

RUN addgroup -g ${gid} ${group} \
    && adduser -D -u ${uid} -G ${group} -s /bin/sh ${user}

USER ${uid}:${gid}

WORKDIR /code

COPY ./ /code

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

COPY ./resources/scripts/$SCRIPT /code/$SCRIPT
RUN chmod +x /code/$SCRIPT

CMD sh $SCRIPT
