FROM jscorptech/django:v0.5

ARG SCRIPT="entrypoint.sh"
ENV SCRIPT=$SCRIPT

ARG user=appuser
ARG group=appuser
ARG uid=1000
ARG gid=1000
RUN groupadd -g ${gid} ${group}
RUN useradd -u ${uid} -g ${group} -s /bin/sh -m ${user} # <--- the '-m' create a user home directory

USER ${uid}:${gid}


WORKDIR /code

COPY ./ /code

RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt

RUN mv ./resources/scripts/$SCRIPT . && chmod +x $SCRIPT

CMD sh $SCRIPT
