# Generated by Django 5.1.3 on 2025-09-16 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chat_id', models.CharField(max_length=255, unique=True, verbose_name='chat id')),
                ('is_register', models.BooleanField(default=False, verbose_name='is register')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='phone')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='full name')),
                ('lang', models.CharField(choices=[('uz', 'uz'), ('ru', 'ru'), ('en', 'en')], default='uz', max_length=255, verbose_name='lang')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=255, verbose_name='key')),
                ('value', models.TextField(verbose_name='value')),
                ('value_uz', models.TextField(null=True, verbose_name='value')),
                ('value_ru', models.TextField(null=True, verbose_name='value')),
                ('value_en', models.TextField(null=True, verbose_name='value')),
            ],
            options={
                'verbose_name': 'messages',
                'verbose_name_plural': 'messages',
                'db_table': 'messages',
            },
        ),
    ]
