# Generated by Django 5.1.3 on 2025-08-27 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'CategoryModel',
                'verbose_name_plural': 'CategoryModels',
                'db_table': 'category',
            },
        ),
        migrations.CreateModel(
            name='ColorModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'ColorModel',
                'verbose_name_plural': 'ColorModels',
                'db_table': 'color',
            },
        ),
        migrations.CreateModel(
            name='SizeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'SizeModel',
                'verbose_name_plural': 'SizeModels',
                'db_table': 'size',
            },
        ),
        migrations.CreateModel(
            name='TagModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'TagModel',
                'verbose_name_plural': 'TagModels',
                'db_table': 'tag',
            },
        ),
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='name')),
                ('desc', models.TextField(verbose_name='desc')),
                ('image', models.ImageField(upload_to='product/', verbose_name='image')),
                ('colors', models.ManyToManyField(to='api.colormodel')),
                ('sizes', models.ManyToManyField(to='api.sizemodel')),
            ],
            options={
                'verbose_name': 'ProductModel',
                'verbose_name_plural': 'ProductModels',
                'db_table': 'product',
            },
        ),
        migrations.CreateModel(
            name='ProductVariantModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.BigIntegerField(default=0, verbose_name='quantiry')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.colormodel')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='api.productmodel')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.sizemodel')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
