# Generated by Django 5.1.3 on 2025-08-27 10:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasketModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.BigIntegerField(default=1, verbose_name='quantiry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.productvariantmodel')),
            ],
            options={
                'verbose_name': 'BasketModel',
                'verbose_name_plural': 'BasketModels',
                'db_table': 'basket',
            },
        ),
    ]
