# Generated by Django 5.1.3 on 2025-08-27 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_ordermodel_itemmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basketmodel',
            name='quantity',
        ),
        migrations.AddField(
            model_name='basketmodel',
            name='count',
            field=models.BigIntegerField(default=1, verbose_name='quantiry'),
        ),
    ]
