# Generated by Django 5.1.3 on 2025-08-27 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_basketmodel_quantity_basketmodel_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='amount'),
        ),
    ]
