# Generated by Django 5.1.3 on 2025-08-27 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_itemmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='amount'),
        ),
    ]
