# Generated by Django 5.1.3 on 2025-08-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_productvariantmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='amount'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='quantity',
            field=models.BigIntegerField(default=0, verbose_name='quantity'),
        ),
    ]
