# Generated by Django 5.1.3 on 2025-08-27 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_productmodel_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='payment_status',
            field=models.BooleanField(default=False, verbose_name='payment status'),
        ),
    ]
