# Generated by Django 5.1.3 on 2025-08-27 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_ordermodel_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemmodel',
            name='amount',
        ),
    ]
