# Generated by Django 5.1.3 on 2025-08-28 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_itemmodel_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemmodel',
            name='amount',
            field=models.BigIntegerField(default=0, verbose_name='amount'),
        ),
    ]
