# Generated by Django 5.1.3 on 2025-09-06 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0010_itemmodel_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="productmodel",
            name="categories",
            field=models.ManyToManyField(related_name="products", to="api.categorymodel"),
        ),
        migrations.AddField(
            model_name="productmodel",
            name="tags",
            field=models.ManyToManyField(related_name="products", to="api.tagmodel"),
        ),
    ]
