# Generated by Django 5.1.3 on 2025-09-06 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_productmodel_categories_productmodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.categorymodel'),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='products', to='api.tagmodel'),
        ),
    ]
