# Generated by Django 5.1.3 on 2025-09-06 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_categorymodel_name_en_categorymodel_name_ru_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.FileField(upload_to='product/', verbose_name='image')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.productmodel')),
            ],
            options={
                'verbose_name': 'ProductimageModel',
                'verbose_name_plural': 'ProductimageModels',
                'db_table': 'productimage',
            },
        ),
    ]
