# Generated by Django 5.1.3 on 2025-09-06 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_productimagemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimagemodel',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.colormodel'),
        ),
    ]
