# Generated by Django 5.1.3 on 2025-09-06 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_productimagemodel_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('delivering', 'delivering'), ('done', 'done'), ('canceled', 'canceled')], default='new', max_length=255, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.colormodel'),
        ),
        migrations.AlterField(
            model_name='productvariantmodel',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.sizemodel'),
        ),
    ]
