# Generated by Django 5.1.3 on 2025-09-06 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_ordermodel_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='status',
            field=models.BooleanField(default=True, verbose_name='status'),
        ),
    ]
