# Generated by Django 5.1.3 on 2025-09-07 07:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_productmodel_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('moysklad_id', models.CharField(max_length=255, verbose_name='moysklad id')),
            ],
            options={
                'verbose_name': 'StoreModel',
                'verbose_name_plural': 'StoreModels',
                'db_table': 'store',
            },
        ),
        migrations.AddField(
            model_name='itemmodel',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storemodel', verbose_name='sklad'),
        ),
    ]
