# Generated by Django 5.1.3 on 2025-09-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_storemodel_itemmodel_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='storemodel',
            name='default',
            field=models.BooleanField(default=False, verbose_name='default'),
        ),
    ]
