# Generated by Django 5.1.3 on 2025-09-07 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_storemodel_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemmodel',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.storemodel', verbose_name='sklad'),
        ),
    ]
