# Generated by Django 5.1.3 on 2025-09-07 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_itemmodel_store'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetailShiftModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('href', models.CharField(max_length=255, verbose_name='mys id')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
            ],
            options={
                'verbose_name': 'RetailshiftModel',
                'verbose_name_plural': 'RetailshiftModels',
                'db_table': 'retailshift',
            },
        ),
        migrations.AddField(
            model_name='productvariantmodel',
            name='href',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='href'),
        ),
    ]
