# Generated by Django 5.1.3 on 2025-09-07 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_retailshiftmodel_productvariantmodel_href'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storemodel',
            name='moysklad_id',
        ),
        migrations.AddField(
            model_name='storemodel',
            name='href',
            field=models.CharField(max_length=255, null=True, verbose_name='href'),
        ),
    ]
