# Generated by Django 5.1.3 on 2025-09-13 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_remove_storemodel_moysklad_id_storemodel_href'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryMethodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
            ],
            options={
                'verbose_name': 'DeliverymethodModel',
                'verbose_name_plural': 'DeliverymethodModels',
                'db_table': 'deliverymethod',
            },
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='adddress',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='delivery address'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverymethodmodel'),
        ),
    ]
