# Generated by Django 5.1.3 on 2025-09-13 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_deliverymethodmodel_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordermodel',
            name='adddress',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='delivery address'),
        ),
    ]
