# Generated by Django 5.1.3 on 2025-09-13 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_ordermodel_adddress_ordermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='href',
            field=models.CharField(blank=True, max_length=500, null=True, verbose_name='href'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='delivery address'),
        ),
    ]
