# Generated by Django 5.1.3 on 2025-09-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_ordermodel_href_alter_ordermodel_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='is_delivery',
            field=models.BooleanField(default=False, verbose_name='is delivery'),
        ),
    ]
