# Generated by Django 5.1.3 on 2025-09-13 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_ordermodel_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverymethodmodel',
            name='price',
            field=models.BigIntegerField(default=0, verbose_name='price'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_method',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverymethodmodel'),
        ),
    ]
