# Generated by Django 5.1.3 on 2025-09-16 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_deliverymethodmodel_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariantmodel',
            name='is_bundle',
            field=models.BooleanField(default=True, verbose_name='is bundle'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='delivery_method',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.deliverymethodmodel'),
        ),
    ]
