# Generated by Django 5.1.3 on 2025-09-16 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_productvariantmodel_is_bundle_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('desc', models.TextField(verbose_name='desc')),
                ('image', models.ImageField(blank=True, null=True, upload_to='notification/', verbose_name='image')),
            ],
            options={
                'verbose_name': 'NotificationModel',
                'verbose_name_plural': 'NotificationModels',
                'db_table': 'notification',
            },
        ),
        migrations.CreateModel(
            name='UserNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.notificationmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'UsernotificationModel',
                'verbose_name_plural': 'UsernotificationModels',
                'db_table': 'usernotification',
            },
        ),
    ]
