# Generated by Django 5.1.3 on 2025-09-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_feedbackmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromocodeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=50, verbose_name='promocode')),
                ('quantity', models.BigIntegerField(default=1, verbose_name='quantity')),
                ('discount', models.BigIntegerField(verbose_name='discount')),
                ('promo_type', models.CharField(choices=[('fixed', 'Fixed'), ('percentage', 'Percentage')], default='fixed', max_length=20, verbose_name='promocode')),
            ],
            options={
                'verbose_name': 'PromocodeModel',
                'verbose_name_plural': 'PromocodeModels',
                'db_table': 'promocode',
            },
        ),
    ]
