# Generated by Django 5.1.3 on 2025-09-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_promocodemodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='promocode',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='promocode'),
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='use_cashback',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='use cashback amount'),
        ),
    ]
