# Generated by Django 5.1.3 on 2025-09-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_ordermodel_promocode_ordermodel_use_cashback'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='promocode_discount',
            field=models.BigIntegerField(default=0, verbose_name='promocode discount'),
        ),
        migrations.AlterField(
            model_name='ordermodel',
            name='use_cashback',
            field=models.BigIntegerField(default=0, verbose_name='use cashback amount'),
        ),
    ]
