# Generated by Django 5.1.3 on 2025-09-26 12:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_ordermodel_promocode_discount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordermodel',
            name='promocode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.promocodemodel', verbose_name='promocode'),
        ),
    ]
