name: Test and Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: make .env
        run: |
          cp /opt/env/.env.test.vesbini /opt/projects/vesbini/_work/vesbini/vesbini/.env

      - name: Build and Start Services for Testing
        run: |
          docker compose -f docker-compose.test.yml build
          docker compose -f docker-compose.test.yml up -d
          make migrate

      - name: Run Tests
        run: |
          docker compose -f docker-compose.test.yml exec -e DJANGO_SETTINGS_MODULE=config.settings.test web pytest -v

      - name: Stop Containers After Test
        if: always()
        run: |
          docker compose -f docker-compose.test.yml down -v

  deploy:
    runs-on: self-hosted
    needs: test   # faqat test muvaffaqiyatli bo‘lsa deploy ishlaydi

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: make .env
        run: |

          cp /opt/env/.env.vesbini /opt/projects/vesbini/_work/vesbini/vesbini/.env

      - name: Run Deployment Script
        run: |
          make deploy-prod
